name: Automatically tag new release
run-name: ${{ github.actor }} tags a new lmd ISO release
on:
  push:
    schedule:
      - cron: '34 5 * * 2'
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Tag release
        uses: tvdias/github-tagger@v0.0.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.date.outputs.date }}

